### PR TITLE
Fix/autocomplete errors

### LINKED ISSUE #1004: [CON-219] Autocomplete errors are spammny
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:*
- Continue:*
- IDE: VS Code
```

### Description

If there is an error with tab-autocomplete, it tends to show up on every keystroke, which is annoying. Ideally, Continue will show any given error the first time, and then not display it a second time.

The error in VS Code is displayed [here](https://github.com/continuedev/continue/blob/d431c60c4dd6ca5e7b67b5ffe30cbc2a20b1b60e/extensions/vscode/src/autocomplete/completionProvider.ts#L18). It's possible that errors are escaping to [here](https://github.com/continuedev/continue/blob/d431c60c4dd6ca5e7b67b5ffe30cbc2a20b1b60e/extensions/vscode/src/autocomplete/completionProvider.ts#L113), but the intended usage is that `onError` gets passed to the CompletionProvider [here](https://github.com/continuedev/continue/blob/d431c60c4dd6ca5e7b67b5ffe30cbc2a20b1b60e/extensions/vscode/src/autocomplete/completionProvider.ts#L41) and then the CompletionProvider handles de-duplicating error messages [here](https://github.com/continuedev/continue/blob/d431c60c4dd6ca5e7b67b5ffe30cbc2a20b1b60e/core/autocomplete/completionProvider.ts#L304-L310). In the last couple of days a few instances of errors on every keystroke have shown up, so there must just be a small mistake in how this is setup.

This should be easy to test by purposefully throwing errors in different spots when debugging and making sure they are properly handled.

### To reproduce

_No response_

### Log output

_No response_

<sub>[CON-219](https://linear.app/continue/issue/CON-219/autocomplete-errors-are-spammny)</sub>

### PR DESCRIPTION
**Pull request by Iamshankhadeep**
fixes #1004

### CODE REVIEW

File: extensions/vscode/src/autocomplete/completionProvider.ts [hunk 1]
```diff
@@ -100,17 +100,15 @@ export class ContinueCompletionProvider
...
           ),
           {
             title: "Log Autocomplete Outcome",
             command: "continue.logAutocompleteOutcome",
             arguments: [outcome, logRejectionTimeout],
-          },
+          }
         ),
       ];
-    } catch (e: any) {
```
Comment (rootedbox) [inline extensions/vscode/src/autocomplete/completionProvider.ts:112]: maybe instead of remove.. post and store the error.. if the next error is the same just ignore.. if it's a new error then post the error

Comment (Iamshankhadeep) [reply extensions/vscode/src/autocomplete/completionProvider.ts:112]:
``` javascript
Telemetry.capture("autocomplete", {
          accepted: outcome.accepted,
          modelName: outcome.modelName,
          modelProvider: outcome.modelProvider,
          time: outcome.time,
          cacheHit: outcome.cacheHit,
});
```
there is 2 instance where the error can occur, one is the upper one and other one is this
``` javascript
new vscode.InlineCompletionItem(
          outcome.completion,
          new vscode.Range(
            position,
            position.translate(0, outcome.completion.length)
          ),
          {
            title: "Log Autocomplete Outcome",
            command: "continue.logAutocompleteOutcome",
            arguments: [outcome, logRejectionTimeout],
          }
        ),
```        
one thing to note here is do we even care to store this and show it to the user ?  cause posthog capture can fail but showing it too the user seems a bit much and with `vscode.InlineCompletionItem` these too. so I thought of removing it.

Comment (sestinj) [reply extensions/vscode/src/autocomplete/completionProvider.ts:112]: I'm actually okay with this. I checked the behavior and VS Code will end up logging the error in the console if something happens in this small area. If something goes wrong here, completions will probably never show up and we'll find out from every user all at once / it will be obvious in testing. In that case I might rather it not spam, and I don't necessarily want to duplicate the logic for showing an error only once (just adds a bit of complexity)

**Review by sestinj — APPROVED** [review]

**Comment by sestinj** [comment]
Nice work and thanks @rootedbox for looking out!

One final thing before I merge: @Iamshankhadeep would be be able to point this PR to the preview branch instead? Here and in the future this is best, so that we have the chance to test the change in pre-release
